title: Products
type: object
properties:
  response: 
    type: "array"
    items: 
      type: "object"
      properties: 
        id: 
          type: "string"
          example: "id"
        vehicle_id: 
          type: "string"
          example: "vehicle_id"
        vin: 
          type: "string"
          example: ":vin"
        display_name: 
          type: "string"
          example: ":name"
        option_codes: 
          type: "string"
          example: "AD15,AF02,AH00,APF0,APH2,APPA,AU00,BCMB,BP00,BR00,BS00,BTX4,CC02,CDM0,CH05,COUS,CW02,DRLH,DSH7,DV4W,FG02,FR01,GLFR,HC00,HP00,IDBO,INBPB,IX01,LP01,LT3B,MDLX,ME02,MI02,PF00,PI01,PK00,PMBL,QLPB,RCX0,RENA,RFPX,S02B,SP00,SR04,ST02,SU01,TIC4,TM00,TP03,TR01,TRA1,TW01,UM01,USSB,UTAB,WT20,X001,X003,X007,X011,X014,X021,X025,X026,X028,X031,X037,X040,X042,YFFC,SC05"
        color: 
          type: "string"
          example: ""
        tokens: 
          type: "array"
          items: 
            type: "string"
          example: 
            - ":token1"
            - ":token2"
        state: 
          type: "string"
          example: "online"
        id_s: 
          type: "string"
          example: ":ids"
        calendar_enabled: 
          type: "boolean"
          example: true
  count: 
    type: "number"
    example: 1
